spring.application.name=ecommerce-amazon-backend

# CONFIGURAÇÕES DO BANCO DE DADOS (POSTGRESQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_amazon
spring.datasource.username=postgres
spring.datasource.password=av7474

# Hibernate (Cria e atualiza as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# CONFIGURAÇÃO DO JWT
api.security.token.secret=${JWT_SECRET:minha-chave-super-secreta-do-projeto-poo-2026-unicap}